#!/bin/bash

module=${1}
device=${1}
mode='664'

group=$(id -gn ${SUDO_USER:-$USER})

/sbin/insmod ./${module}.ko || exit 1

# remove stale nodes
rm -f /dev/${device}

major=$(awk -v m=$module '$2 == m {print $1}' /proc/devices)

mknod /dev/${device} c $major 0

chgrp $group /dev/${device}
chmod $mode /dev/${device}
